name = "ABC"
uuid = "f50d89cf-913a-4367-bef2-bd444eca16c0"
authors = ["Florian <zink.florian@gmail.com> and contributors"]
version = "0.1.0"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"

[compat]
julia = "1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
